const Futbolcular =  [
    {
      id: 1,
      formaNumarasi: "1",
      adi: "Ersin",
      soyadi: "Destanoğlu",
      dogumTarihi: "01/01/2001",
      dogumYeri: "İstanbul",
      uyruk: "Türkiye",
      boy: "1,95 m",
      mevki: "Kaleci",
      mevkiID: 1,
      resim:
        "https://img.a.transfermarkt.technology/portrait/header/500091-1674487079.png?lm=1",
      rating: 75,
    },
    {
      id: 2,
      formaNumarasi: "34",
      adi: "Mert",
      soyadi: "Günok",
      dogumTarihi: "01/03/1989",
      dogumYeri: "Karabük",
      uyruk: "Türkiye",
      boy: "1,96 m",
      mevki: "Kaleci",
      mevkiID: 1,
      resim:
        "https://img.a.transfermarkt.technology/portrait/header/51894-1623407336.png?lm=1",
      rating: 73,
    },
    {
      id: 3,
      formaNumarasi: "99",
      adi: "Emre",
      soyadi: "Bilgin",
      dogumTarihi: "26/02/2004",
      dogumYeri: "İstanbul",
      uyruk: "Türkiye",
      boy: "1,88 m",
      mevki: "Kaleci",
      mevkiID: 1,
      resim:
        "https://img.a.transfermarkt.technology/portrait/big/727147-1667043951.png?lm=1",
      rating: 62,
    },
    {
      id: 4,
      formaNumarasi: "97",
      adi: "Utku",
      soyadi: "Yuvakuran",
      dogumTarihi: "02/11/1997",
      dogumYeri: "İstanbul",
      uyruk: "Türkiye",
      boy: "1,92 m",
      mevki: "Kaleci",
      mevkiID: 1,
      resim:
        "https://img.a.transfermarkt.technology/portrait/big/342995-1674550386.png?lm=1",
      rating: 66,
    },
    {
      id: 5,
      formaNumarasi: "26",
      adi: "Romain",
      soyadi: "Saïss",
      dogumTarihi: "26/03/1990",
      dogumYeri: "Bourg-de-Péage",
      uyruk: "Fas",
      boy: "1,88 m",
      mevki: "Stoper",
      mevkiID: 2,
      resim:
        "https://img.a.transfermarkt.technology/portrait/big/204198-1666278687.png?lm=1",
      rating: 77,
    },
    {
      id: 6,
      formaNumarasi: "3",
      adi: "Tayyip Talha",
      soyadi: "Sanuç",
      dogumTarihi: "17/12/1999",
      dogumYeri: "Karabük",
      uyruk: "Türkiye",
      boy: "1,88 m",
      mevki: "Stoper",
      mevkiID: 2,
      resim:
        "https://img.a.transfermarkt.technology/portrait/big/462772-1666279231.png?lm=1",
      rating: 65,
    },
    {
      id: 7,
      formaNumarasi: "6",
      adi: "Omar",
      soyadi: "Colley",
      dogumTarihi: "24/10/1992",
      dogumYeri: "Lamin",
      uyruk: "Gambiya",
      boy: "1,91 m",
      mevki: "Stoper",
      mevkiID: 2,
      resim:
        "https://img.a.transfermarkt.technology/portrait/big/174733-1595859915.jpg?lm=1://img.a.transfermarkt.technology/portrait/big/462772-1666279231.png?lm=1",
      rating: 75,
    },
    {
      id: 8,
      formaNumarasi: "20",
      adi: "Necip",
      soyadi: "Uysal",
      dogumTarihi: "24/01/1991",
      dogumYeri: "İstanbul",
      uyruk: "Türkiye",
      boy: "1,80 m",
      mevki: "Stoper",
      mevkiID: 2,
      resim:
        "https://img.a.transfermarkt.technology/portrait/big/77710-1667045349.png?lm=1",
      rating: 69,
    },    
    {
      id: 9,
      formaNumarasi: "23",
      adi: "Welinton Souza",
      soyadi: "Silva",
      dogumTarihi: "10/04/1989",
      dogumYeri: "Rio de Janeiro",
      uyruk: "Brezilya",
      boy: "1,81 m",
      mevki: "Stoper",
      mevkiID: 2,
      resim:
        "https://img.a.transfermarkt.technology/portrait/big/95152-1667045167.png?lm=1",
      rating: 74,
    },
    {
      id: 10,
      formaNumarasi: "25",
      adi: "Arthur",
      soyadi: "Masuaku",
      dogumTarihi: "07/11/1993",
      dogumYeri: "Lille",
      uyruk: "Kongo DC",
      boy: "1,79 m",
      mevki: "Sol Bek",
      mevkiID: 2,
      resim:
        "https://img.a.transfermarkt.technology/portrait/big/181380-1666280141.png?lm=1",
      rating: 75,
    },
    {
      id: 11,
      formaNumarasi: "77",
      adi: "Umut",
      soyadi: "Meraş",
      dogumTarihi: "20/12/1995",
      dogumYeri: "İstanbul",
      uyruk: "Türkiye",
      boy: "1,78 m",
      mevki: "Sol Bek",
      mevkiID: 2,
      resim:
        "https://img.a.transfermarkt.technology/portrait/big/341549-1666706073.png?lm=1",
      rating: 69,
    },
    {
      id: 12,
      formaNumarasi: "2",
      adi: "Valentin",
      soyadi: "Rosier",
      dogumTarihi: "19/08/1996",
      dogumYeri: "Montauban",
      uyruk: "Fransa",
      boy: "1,75 m",
      mevki: "Sağ Bek",
      mevkiID: 2,
      resim:
        "https://img.a.transfermarkt.technology/portrait/big/441170-1666619891.png?lm=1",
      rating: 77,
    },
    {
      id: 13,
      formaNumarasi: "4",
      adi: "Onur",
      soyadi: "Bulut",
      dogumTarihi: "16/04/1994",
      dogumYeri: "Werdohl",
      uyruk: "Türkiye",
      boy: "1,79 m",
      mevki: "Sağ Bek",
      mevkiID: 2,
      resim:
        "https://img.a.transfermarkt.technology/portrait/big/152733-1669738590.png?lm=1",
      rating: 68,
    },
    {
      id: 14,
      formaNumarasi: "88",
      adi: "Tayfur",
      soyadi: "Bingöl",
      dogumTarihi: "11/01/1993",
      dogumYeri: "Ankara",
      uyruk: "Türkiye",
      boy: "1,80 m",
      mevki: "Sağ Bek",
      mevkiID: 2,
      resim:
        "https://img.a.transfermarkt.technology/portrait/big/184440-1666704815.png?lm=1",
      rating: 67,
    },
    {
      id: 15,
      formaNumarasi: "19",
      adi: "Amir",
      soyadi: "Hadziahmetovic",
      dogumTarihi: "08/03/1997",
      dogumYeri: "Nexø",
      uyruk: "Bosna-Hersek",
      boy: "1,79 m",
      mevki: "Önlibero",
      mevkiID: 3,
      resim:
        "https://img.a.transfermarkt.technology/portrait/big/293213-1669903721.png?lm=1",
      rating: 74,
    },
    {
      id: 16,
      formaNumarasi: "22",
      adi: "Berkay",
      soyadi: "Vardar",
      dogumTarihi: "14/01/2003",
      dogumYeri: "İstanbul",
      uyruk: "Türkiye",
      boy: "1,88 m",
      mevki: "Önlibero",
      mevkiID: 3,
      resim:
        "https://img.a.transfermarkt.technology/portrait/big/724350-1667044972.png?lm=1",
      rating: 63,
    },
    {
      id: 17,
      formaNumarasi: "13",
      adi: "Atiba",
      soyadi: "Hutchinson",
      dogumTarihi: "08/02/1983",
      dogumYeri: "Brampton, Ontario",
      uyruk: "Kanada",
      boy: "1,87 m",
      mevki: "Önlibero",
      mevkiID: 3,
      resim:
        "https://img.a.transfermarkt.technology/portrait/big/16101-1667043797.png?lm=1",
      rating: 72,
    },
    {
      id: 18,
      formaNumarasi: "83",
      adi: "Gedson",
      soyadi: "Fernandes",
      dogumTarihi: "09/01/1999",
      dogumYeri: "São Tomé",
      uyruk: "Portekiz",
      boy: "1,83 m",
      mevki: "Merkez orta saha",
      mevkiID: 3,
      resim:
        "https://img.a.transfermarkt.technology/portrait/big/337800-1666705625.png?lm=1",
      rating: 77,
    },
    {
      id: 19,
      formaNumarasi: "8",
      adi: "Salih",
      soyadi: "Uçan",
      dogumTarihi: "06/01/1994",
      dogumYeri: "Muğla",
      uyruk: "Türkiye",
      boy: "1,82 m",
      mevki: "Merkez orta saha",
      mevkiID: 3,
      resim:
        "https://img.a.transfermarkt.technology/portrait/big/170838-1666618454.png?lm=1",
      rating: 73,
    },
    {
      id: 20,
      formaNumarasi: "17",
      adi: "Kerem Atakan",
      soyadi: "Kesgin",
      dogumTarihi: "05/11/2000",
      dogumYeri: "Tokat",
      uyruk: "Türkiye",
      boy: "1,76 m",
      mevki: "Merkez orta saha",
      mevkiID: 3,
      resim:
        "https://img.a.transfermarkt.technology/portrait/big/361264-1666362882.png?lm=1",
      rating: 66,
    },
    {
      id: 21,
      formaNumarasi: "11",
      adi: "Dele",
      soyadi: "Alli",
      dogumTarihi: "11/04/1996",
      dogumYeri: "Milton Keynes",
      uyruk: "İngiltere",
      boy: "1,88 m",
      mevki: "On Numara",
      mevkiID: 3,
      resim:
        "https://img.a.transfermarkt.technology/portrait/big/207929-1665670825.png?lm=1",
      rating: 77,
    },
    {
      id: 22,
      formaNumarasi: "44",
      adi: "Alexandru",
      soyadi: "Maxim",
      dogumTarihi: "08/07/1990",
      dogumYeri: "Piatra Neamţ",
      uyruk: "Romanya",
      boy: "1,77 m",
      mevki: "On Numara",
      mevkiID: 3,
      resim:
        "https://img.a.transfermarkt.technology/portrait/big/129513-1665493287.png?lm=1",
      rating: 75,
    },
    {
      id: 23,
      formaNumarasi: "15",
      adi: "Nathan",
      soyadi: "Redmond",
      dogumTarihi: "06/03/1994",
      dogumYeri: "Birmingham",
      uyruk: "İngiltere",
      boy: "1,73 m",
      mevki: "Sol Kanat",
      mevkiID: 3,
      resim:
        "https://img.a.transfermarkt.technology/portrait/big/129078-1666280539.png?lm=1",
      rating: 75,
    },
    {
      id: 24,
      formaNumarasi: "7",
      adi: "Georges-Kevin",
      soyadi: "N'Koudou",
      dogumTarihi: "13/02/1995",
      dogumYeri: "Versailles",
      uyruk: "Kamerun",
      boy: "1,72 m",
      mevki: "Sol Kanat",
      mevkiID: 3,
      resim:
        "https://img.a.transfermarkt.technology/portrait/big/215679-1667044766.png?lm=1",
      rating: 75,
    },
    {
      id: 25,
      formaNumarasi: "18",
      adi: "Rachid",
      soyadi: "Ghezzal",
      dogumTarihi: "09/05/1992",
      dogumYeri: "Décines-Charpieu",
      uyruk: "Cezayir",
      boy: "1,82 m",
      mevki: "Sağ Kanat",
      mevkiID: 3,
      resim:
        "https://img.a.transfermarkt.technology/portrait/big/118287-1666619497.png?lm=1",
      rating: 79,
    },
    {
      id: 26,
      formaNumarasi: "40",
      adi: "Jackson",
      soyadi: "Muleka",
      dogumTarihi: "04/10/1999",
      dogumYeri: "Lubumbashi",
      uyruk: "Kongo DC",
      boy: "1,80 m",
      mevki: "Santrafor",
      mevkiID: 4,
      resim:
        "https://img.a.transfermarkt.technology/portrait/big/549966-1666363881.png?lm=1",
      rating: 71,
    },
    {
      id: 27,
      formaNumarasi: "10",
      adi: "Vincent",
      soyadi: "Aboubakar",
      dogumTarihi: "22/01/1992",
      dogumYeri: "Garoua",
      uyruk: "Kamerun",
      boy: "1,84 m",
      mevki: "Santrafor",
      mevkiID: 4,
      resim:
        "https://img.a.transfermarkt.technology/portrait/big/147487-1674477789.png?lm=1",
      rating: 75,
    },
    {
      id: 28,
      formaNumarasi: "9",
      adi: "Cenk",
      soyadi: "Tosun",
      dogumTarihi: "07/06/1991",
      dogumYeri: "Wetzlar",
      uyruk: "Türkiye",
      boy: "1,83 m",
      mevki: "Santrafor",
      mevkiID: 4,
      resim:
        "https://img.a.transfermarkt.technology/portrait/big/45671-1666363106.png?lm=1",
      rating: 73,
    }
  ];

export default Futbolcular;